In [8]:
import numpy as np
import pandas as pd
from pylab import plt, mpl
plt.style.use('seaborn')
mpl.rcParams['font.family'] = 'serif'
%matplotlib inline

import pickle
from random import gauss

In [9]:
a = [gauss(1.5, 2) for i in range(1000000)]

In [12]:
path = '/Users/sagehuseas/Desktop/python_finance/'
pkl_file = open(path + 'data.pkl', 'wb')

In [13]:
%time pickle.dump(a, pkl_file)

CPU times: user 28.4 ms, sys: 8.83 ms, total: 37.2 ms
Wall time: 36.2 ms


In [14]:
pkl_file.close()

In [15]:
ll $path

total 17600
-rw-r--r--   1 sagehuseas  staff     1064 Oct 22 09:46 LICENSE
-rw-r--r--   1 sagehuseas  staff       16 Oct 22 09:46 README.md
-rw-r--r--   1 sagehuseas  staff  9002006 Oct 25 16:05 data.pkl
drwxr-xr-x  12 sagehuseas  staff      384 Oct 25 16:03 notebooks/


In [16]:
pkl_file = open(path + 'data.pkl', 'rb')

In [17]:
%time b = pickle.load(pkl_file)

CPU times: user 38.8 ms, sys: 18.2 ms, total: 57 ms
Wall time: 55.1 ms


In [18]:
a[:3]

[1.7869947082189621, 1.9838227925505596, 4.578663971820635]

In [19]:
b[:3]

[1.7869947082189621, 1.9838227925505596, 4.578663971820635]

In [20]:
np.allclose(np.array(a), np.array(b))

True

In [21]:
pkl_file = open(path + 'data.pkl', 'wb')
%time pickle.dump(np.array(a), pkl_file)

CPU times: user 30.2 ms, sys: 7.11 ms, total: 37.3 ms
Wall time: 36.7 ms


In [22]:
%time pickle.dump(np.array(a) ** 2, pkl_file)

CPU times: user 52.1 ms, sys: 8.84 ms, total: 61 ms
Wall time: 42.6 ms


In [23]:
pkl_file.close()

In [24]:
ll $path

total 31272
-rw-r--r--   1 sagehuseas  staff      1064 Oct 22 09:46 LICENSE
-rw-r--r--   1 sagehuseas  staff        16 Oct 22 09:46 README.md
-rw-r--r--   1 sagehuseas  staff  16000322 Oct 25 16:08 data.pkl
drwxr-xr-x  12 sagehuseas  staff       384 Oct 25 16:07 notebooks/


In [25]:
pkl_file = open(path + 'data.pkl', 'rb')
x = pickle.load(pkl_file)
x[:4]

array([1.78699471, 1.98382279, 4.57866397, 0.05252152])

In [26]:
y = pickle.load(pkl_file)
y[:4]

array([3.19335009e+00, 3.93555287e+00, 2.09641638e+01, 2.75850973e-03])

In [27]:
pkl_file.close()

Pickle operates on first in first out (FIFO) principle - above retrieves object that was stored first, then retrieves second

### Reading and Writing Text Files

In [28]:
rows = 5000
a = np.random.standard_normal((rows, 5)).round(4)
a

array([[ 0.585 , -0.9334, -1.123 ,  0.5545,  0.012 ],
       [-0.3035, -0.2686,  0.1633,  0.4313,  0.9214],
       [-0.2123,  0.2739, -0.0316, -0.6931,  1.1389],
       ...,
       [ 0.2182,  1.8889,  0.6397, -0.134 ,  0.4924],
       [ 0.9827, -0.404 ,  0.4376, -0.3832,  0.0538],
       [-0.48  , -0.595 , -1.0523,  0.0113,  1.2146]])

In [29]:
t = pd.date_range(start = '2019/1/1', periods = rows, freq = 'H') # H for hourly intervals
t

DatetimeIndex(['2019-01-01 00:00:00', '2019-01-01 01:00:00',
               '2019-01-01 02:00:00', '2019-01-01 03:00:00',
               '2019-01-01 04:00:00', '2019-01-01 05:00:00',
               '2019-01-01 06:00:00', '2019-01-01 07:00:00',
               '2019-01-01 08:00:00', '2019-01-01 09:00:00',
               ...
               '2019-07-27 22:00:00', '2019-07-27 23:00:00',
               '2019-07-28 00:00:00', '2019-07-28 01:00:00',
               '2019-07-28 02:00:00', '2019-07-28 03:00:00',
               '2019-07-28 04:00:00', '2019-07-28 05:00:00',
               '2019-07-28 06:00:00', '2019-07-28 07:00:00'],
              dtype='datetime64[ns]', length=5000, freq='H')

In [30]:
csv_file = open(path + 'data.csv', 'w')
header = 'date,no1,no2,no3,no4,no5\n'
csv_file.write(header)

25

In [31]:
for t_, (no1, no2, no3, no4, no5) in zip(t, a):
    s = '{}, {}, {}, {}, {}, {}\n'.format(t_, no1, no2, no3, no4, no5)
    csv_file.write(s)

In [32]:
csv_file.close()

In [33]:
ll $path

total 31880
-rw-r--r--   1 sagehuseas  staff      1064 Oct 22 09:46 LICENSE
-rw-r--r--   1 sagehuseas  staff        16 Oct 22 09:46 README.md
-rw-r--r--   1 sagehuseas  staff    309752 Oct 25 16:15 data.csv
-rw-r--r--   1 sagehuseas  staff  16000322 Oct 25 16:08 data.pkl
drwxr-xr-x  12 sagehuseas  staff       384 Oct 25 16:15 notebooks/


### SQL database

In [34]:
import sqlite3 as sq3

In [35]:
con = sq3.connect(path + 'numbs.db')

In [37]:
query = 'CREATE TABLE numbs (Date date, No1 real, no2 real)'
con.execute(query)

In [38]:
con.commit()

In [39]:
q = con.execute

In [40]:
q('SELECT * FROM sqlite_master').fetchall()

[('table',
  'numbs',
  'numbs',
  2,
  'CREATE TABLE numbs (Date date, No1 real, no2 real)')]

In [41]:
import datetime
now = datetime.datetime.now()
q('INSERT INTO numbs VALUES(?, ?, ?)', (now, 0.12, 7.3))

In [42]:
np.random.seed(100)

In [43]:
data = np.random.standard_normal((10000, 2)).round(4)

In [44]:
%%time
for row in data:
    now = datetime.datetime.now()
    q('INSERT INTO numbs VALUES(?, ?, ?)', (now, row[0], row[1]))
con.commit()

CPU times: user 79 ms, sys: 4.09 ms, total: 83.1 ms
Wall time: 83.5 ms


In [45]:
q('SELECT * FROM numbs').fetchmany(4)

[('2018-10-25 16:21:01.847046', 0.12, 7.3),
 ('2018-10-25 16:22:31.253537', -1.7498, 0.3427),
 ('2018-10-25 16:22:31.253620', 1.153, -0.2524),
 ('2018-10-25 16:22:31.253653', 0.9813, 0.5142)]

In [46]:
q('SELECT * FROM numbs WHERE no1 > 0.5').fetchmany(4)

[('2018-10-25 16:22:31.253620', 1.153, -0.2524),
 ('2018-10-25 16:22:31.253653', 0.9813, 0.5142),
 ('2018-10-25 16:22:31.254209', 0.6727, -0.1044),
 ('2018-10-25 16:22:31.254814', 1.619, 1.5416)]

In [47]:
pointer = q('SELECT * FROM numbs')

In [48]:
for i in range(3):
    print(pointer.fetchone())

('2018-10-25 16:21:01.847046', 0.12, 7.3)
('2018-10-25 16:22:31.253537', -1.7498, 0.3427)
('2018-10-25 16:22:31.253620', 1.153, -0.2524)


In [49]:
rows = pointer.fetchall()
rows[:3]

[('2018-10-25 16:22:31.253653', 0.9813, 0.5142),
 ('2018-10-25 16:22:31.253688', 0.2212, -1.07),
 ('2018-10-25 16:22:31.253700', -0.1895, 0.255)]

In [52]:
q('DROP TABLE IF EXISTS numbs')

In [53]:
q('SELECT * FROM sqlite_master').fetchall()

[]

In [54]:
con.close()